accounts/urls.py
# This file is covered by the BSD license. See LICENSE in the root directory.
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetDoneView
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout', LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'),
    path('register', views.register, name='register'),
    path('activate/<str:uid>/<slug:token>', views.activate, name='activate'),
    path('profile', views.profile, name='profile'),
    path('change-password', views.change_password, name='change_password'),
    path('reset-password', PasswordResetView.as_view(
        template_name='accounts/reset_password.html',
        success_url='/accounts/reset-password/done',
        email_template_name='accounts/reset_password_email.html'),
         name='reset_password'),
    path('reset-password/done', PasswordResetDoneView.as_view(
        template_name='accounts/reset_password_done.html')),
    path('reset-password/confirm<str:uidb64>/<slug:token>/',
         PasswordResetConfirmView.as_view(
             template_name='accounts/reset_password_confirm.html',
             success_url='/accounts/reset-password/complete'),
         name='password_reset_confirm'),
    path('reset-password/complete', PasswordResetCompleteView.as_view(
        template_name='accounts/reset_password_complete.html')),
]

mainproject/urls.py
# This file is covered by the BSD license. See LICENSE in the root directory.
"""MatD3 URL Configuration.

"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import generic

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', generic.TemplateView.as_view(
        template_name='mainproject/home.html'), name='index'),
    path('contact/', generic.TemplateView.as_view(
        template_name='mainproject/contact.html'), name='contact'),
    path('contributors/', views.contributors, name='contributors'),
    path('materials/', include('materials.urls')),
    path('accounts/', include('accounts.urls')),
    path('nested_admin/', include('nested_admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
# This file is covered by the BSD license. See LICENSE in the root directory.
from django.urls import include
from django.urls import path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register('references', views.ReferenceViewSet)
router.register('systems', views.SystemViewSet)
router.register('properties', views.PropertyViewSet)
router.register('units', views.UnitViewSet)
router.register('datasets', views.DatasetViewSet)

app_name = 'materials'
urlpatterns = [
    path('', include(router.urls)),
    path('search', views.SearchFormView.as_view(), name='search'),
    path('<int:pk>', views.SystemView.as_view(), name='system'),
    path('dataset/<int:pk>', views.DatasetView.as_view(), name='dataset'),
    path('dataset/<int:pk>/toggle-visibility/<str:view_name>',
         views.toggle_visibility, name='toggle_visibility'),
    path('dataset/<int:pk>/toggle-is-figure/<str:view_name>',
         views.toggle_is_figure, name='toggle_is_figure'),
    path('dataset/<int:pk>/delete/<str:view_name>',
         views.delete_dataset, name='delete_dataset'),
    path('dataset/<int:pk>/verify/<str:view_name>',
         views.verify_dataset, name='verify_dataset'),
    path('add-data', views.AddDataView.as_view(), name='add_data'),
    path('submit-data', views.submit_data, name='submit_data'),
    path('reference/<int:pk>', views.ReferenceDetailView.as_view(),
         name='reference'),
    path('autofill-input-data', views.autofill_input_data),
    path('<int:system_pk>/property-all-entries/<int:prop_pk>',
         views.PropertyAllEntriesView.as_view(), name='property_all_entries'),
    path('data-for-chart/<int:pk>', views.data_for_chart,
         name='data_for_chart'),
    path('get-atomic-coordinates/<int:pk>', views.get_atomic_coordinates,
         name='get_atomic_coordinates'),
    path('get-subset-values/<int:pk>', views.get_subset_values,
         name='get_subset_values'),
    path('get-jsmol-input/<int:pk>', views.get_jsmol_input,
         name='get_jsmol_input'),
    path('report-issue', views.report_issue, name='report_issue'),
    path('extract-k-from-control-in', views.extract_k_from_control_in),
    path('linked-data/<int:pk>', views.LinkedDataView.as_view(),
         name='linked_data'),
    path('prefilled-form/<int:pk>', views.prefilled_form,
         name='prefilled_form'),
]

materials/views.py
# This file is covered by the BSD license. See LICENSE in the root directory.
from functools import reduce
import io
import logging
import operator
import os
import re
import requests
import zipfile

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.files.uploadedfile import UploadedFile
from django.core.mail import send_mail
from django.db import transaction
from django.db.models import BooleanField
from django.db.models import Case
from django.db.models import Q
from django.db.models import Value
from django.db.models import When
from django.db.models.fields import TextField
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import reverse
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.views import generic
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from . import forms
from . import models
from . import permissions
from . import qresp
from . import serializers
from . import utils

logger = logging.getLogger(__name__)


def dataset_author_check(view):
    """Test whether the logged on user is the creator of the data set."""
    @login_required
    def wrap(request, *args, **kwargs):
        dataset = get_object_or_404(models.Dataset, pk=kwargs['pk'])
        if dataset.created_by == request.user:
            return view(request, *args, **kwargs)
        else:
            logger.warning(f'Data set was created by {dataset.created_by} but '
                           'an attempt was made to delete it by '
                           f'{request.user}',
                           extra={'request': request})
            return HttpResponseForbidden()
    wrap.__doc__ = view.__doc__
    wrap.__name__ = view.__name__
    return wrap


def staff_status_required(view):
    @login_required
    def wrap(request, *args, **kwargs):
        if request.user.is_staff:
            return view(request, *args, **kwargs)
        else:
            logger.warning(f'{request.user.username} is trying to submit data '
                           'but does not have staff status.',
                           extra={'request': request})
            return HttpResponseForbidden()
    wrap.__doc__ = view.__doc__
    wrap.__name__ = view.__name__
    return wrap


class StaffStatusMixin(LoginRequiredMixin):
    """Verify that the current user is at least staff."""
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class SystemView(generic.ListView):
    template_name = 'materials/system.html'
    context_object_name = 'dataset_list'

    def get_queryset(self, **kwargs):
        return models.Dataset.objects.filter(
            system__pk=self.kwargs['pk']).annotate(is_atomic_structure=Case(
                When(primary_property__name='atomic structure',
                     then=Value(True)),
                default=Value(False), output_field=BooleanField())).order_by(
                    '-is_atomic_structure')


class PropertyAllEntriesView(generic.ListView):
    """Display all data sets for a given property and system."""
    template_name = 'materials/property_all_entries.html'

    def get_queryset(self, **kwargs):
        return models.Dataset.objects.filter(
            system__pk=self.kwargs['system_pk']).filter(
                primary_property__pk=self.kwargs['prop_pk'])


class ReferenceDetailView(generic.DetailView):
    model = models.Reference


class DatasetView(generic.ListView):
    """Display information about a single data set.

    This is defined as a ListView so that we can reuse the same
    template as for PropertyAllEntriesView. Otherwise, this is really
    a DetailView.

    """
    template_name = 'materials/property_all_entries.html'

    def get_queryset(self, **kwargs):
        return models.Dataset.objects.filter(pk=self.kwargs['pk'])


class LinkedDataView(generic.ListView):
    """Returns data sets that are linked to each other."""
    template_name = 'materials/linked_data.html'

    def get_queryset(self, **kwargs):
        dataset = models.Dataset.objects.get(pk=self.kwargs['pk'])
        datasets = dataset.linked_to.all()
        return list(datasets) + [dataset]


class SearchFormView(generic.TemplateView):
    """Search for system page"""
    template_name = 'materials/search.html'
    search_terms = [
        ['formula', 'Formula'],
        ['organic', 'Organic Component'],
        ['inorganic', 'Inorganic Component'],
        ['author', 'Author']
    ]

    def get(self, request):
        return render(request, self.template_name,
                      {'search_terms': self.search_terms})

    def post(self, request):
        template_name = 'materials/search_results.html'
        form = forms.SearchForm(request.POST)
        search_text = ''
        # default search_term
        search_term = 'formula'
        if form.is_valid():
            search_text = form.cleaned_data['search_text']
            search_term = request.POST.get('search_term')
            systems_info = []
            if search_term == 'formula':
                systems = models.System.objects.filter(
                    Q(formula__icontains=search_text) |
                    Q(group__icontains=search_text) |
                    Q(compound_name__icontains=search_text)).order_by(
                        'formula')
            elif search_term == 'organic':
                systems = models.System.objects.filter(
                    organic__contains=search_text).order_by('organic')
            elif search_term == 'inorganic':
                systems = models.System.objects.filter(
                    inorganic__contains=search_text).order_by('inorganic')
            elif search_term == 'author':
                keywords = search_text.split()
                query = reduce(operator.or_, (
                    Q(dataset__reference__authors__last_name__icontains=x) for
                    x in keywords))
                systems = models.System.objects.filter(query).distinct()
            else:
                raise KeyError('Invalid search term.')

        args = {
            'systems': systems,
            'search_term': search_term,
            'systems_info': systems_info
        }
        return render(request, template_name, args)


class AddDataView(StaffStatusMixin, generic.TemplateView):
    """View for submitting user data.

    The arguments are only meant to be used when this view is called
    from external sites. Fields such as the reference can be prefilled
    then.

    """
    template_name = 'materials/add_data.html'

    def get(self, request, *args, **kwargs):
        main_form = forms.AddDataForm()
        if request.GET.get('return-url'):
            base_template = 'mainproject/base.html'
            main_form.fields['return_url'].initial = request.GET.get(
                'return-url')
        else:
            base_template = 'materials/base.html'
        if request.GET.get('reference'):
            main_form.fields['fixed_reference'].initial = (
                models.Reference.objects.get(pk=request.GET.get('reference')))
        if request.GET.get('qresp-fetch-url'):
            qresp_fetch_url = request.GET.get('qresp-fetch-url')
            paper_detail = requests.get(qresp_fetch_url).json()
            main_form.fields['qresp_fetch_url'].initial = qresp_fetch_url
            chart_nr = int(request.GET.get('qresp-chart-nr'))
            main_form.fields['qresp_chart_nr'].initial = chart_nr
            main_form.fields['caption'].initial = (
                paper_detail['_PaperDetails__charts'][chart_nr]['caption'])
        return render(request, self.template_name, {
            'main_form': main_form,
            'reference_form': forms.AddReferenceForm(),
            'system_form': forms.AddSystemForm(),
            'property_form': forms.AddPropertyForm(),
            'unit_form': forms.AddUnitForm(),
            'base_template': base_template,
        })


class ReferenceViewSet(viewsets.ModelViewSet):
    queryset = models.Reference.objects.all()
    serializer_class = serializers.ReferenceSerializer
    permission_classes = (permissions.IsStaffOrReadOnly,)

    @transaction.atomic
    def perform_create(self, serializer):
        """Save reference and optionally create authors.

        The combination first name/last name/institution must be
        unique. If not, the given author is not in the database
        yet. Note that this constraint can't be enforced at the
        database level because of the limitations of the length of the
        key.

        """
        reference = serializer.save()
        for name in self.request.POST:
            if name.startswith('first-name-'):
                counter = name.split('first-name-')[1]
                first_name = self.request.POST[name]
                last_name = self.request.POST[f'last-name-{counter}']
                institution = self.request.POST[f'institution-{counter}']
                authors = models.Author.objects.filter(
                    first_name=first_name).filter(last_name=last_name).filter(
                        institution=institution)
                if authors:
                    author = authors[0]
                else:
                    author = models.Author.objects.create(
                        first_name=first_name,
                        last_name=last_name,

materials/templates/materials/base.html
{% extends 'mainproject/base.html' %}

{% block navbar %}
  <nav class="navbar navbar-expand-md">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">{{ mat3d_name }}</a>
      <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse"
              data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'materials:search' %}">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://hybrid3.duke.edu/">HybriD<sup>3</sup> project</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contributors">Contributors</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://hybrid3-database.readthedocs.io/en/latest/">
              Software behind the database
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'materials:add_data' %}">Add Data</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
            </li>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
              </li>
            </ul>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

materials/templates/materials/dataset_buttons.html
{% if dataset.secondary_property %}
  <a href="{% url 'materials:toggle_is_figure' pk=dataset.pk view_name=request.resolver_match.url_name %}"
     class="btn btn-success">
    {% if dataset.is_figure %}
      Show table
    {% else %}
      Show figure
    {% endif %}
  </a>
{% endif %}
<a href="{% url 'materials:toggle_visibility' pk=dataset.pk view_name=request.resolver_match.url_name %}"
   class="btn btn-success">
  {% if dataset.visible %}
    Unpublish
  {% else %}
    Publish
  {% endif %}
</a>
<a href="{% url 'admin:materials_dataset_change' dataset.pk %}" class="btn btn-success">
  Edit
</a>
<button data-reverse-url=
        "{% url 'materials:delete_dataset' pk=dataset.pk view_name=request.resolver_match.url_name %}"
        type="button" class="btn btn-danger delete-button">
  Delete
</button>

materials/templates/materials/dataset_scripts.html
{% load static %}

{# These functions are used for each instance of dataset_contents.html #}

<script src="{% static 'materials/javascript/plot_data.js' %}"></script>
<script src="{% static 'materials/javascript/delete_button.js' %}"></script>
<script src="{% static 'materials/javascript/verify_button.js' %}"></script>
<script src="{% static 'materials/javascript/expand_hide_button.js' %}"></script>
<script src="{% static 'materials/javascript/fetch_subset_values.js' %}"></script>
{# Atomic structure specific #}
<script src="{% static 'materials/javascript/show_atomic_structure.js' %}"></script>

materials/templates/materials/input_field.html
{% load materials_tags %}

{% if inline %}<div class="input-group">{% endif %}

  {% if field.field.widget.input_type == 'checkbox' %}
    {# CHECKBOX #}
    {{ field }}
    <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
    <div class="ml-1">
      {{ field.help_text|tooltip }}
    </div>
  {% elif field.field.widget.input_type == 'radio' %}
    {# RADIO #}
    <legend class="col-form-label">
      {{ field.label }}
      {{ field.help_text|tooltip }}
    </legend>
    {% for radio in field %}
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" id="{{ radio.id_for_label }}"
               name="{{ field.name }}" value="{{ radio.data.value }}"
               {% if radio.data.attrs.checked %}checked{% endif %}>
        <label class="form-check-label" for="{{ radio.id_for_label }}">
          {{ radio.choice_label|capfirst }}
        </label>
      </div>
    {% endfor %}
  {% else %}
    {# OTHERS #}
    {% if inline %}<div class="mt-2 mr-2">{% endif %}
    {{ field.label_tag }}
    {{ field.help_text|tooltip }}
    {% if inline %}</div>{% endif %}
    {% if field.field.widget.input_type == 'select' %}
      <select id="{{ field.id_for_label }}" name="{{ field.name }}"
              placeholder="--select or add new--" hidden>
      </select>
    {% else %}
      {{ field }}
    {% endif %}
  {% endif %}

{% if inline %}</div>{% endif %}

{% if field.errors %}
  <p class="alert alert-danger">{{ field.errors.as_text }}</p>
{% endif %}

materials/templates/materials/jsmol_card.html
<h1>&nbsp;</h1>
<div class="card">
  <div class="card-header">Atomic coordinates</div>
  <div class="card-body">
    <div id="jmol"></div>
    <br>
    {% for subset in dataset.subsets.all %}
      {% if subset.first_with_atomic_coordinates %}
        <div class="text-center">
          <button class="text-center btn btn-default expand-hide-button"
                  data-toggle="collapse"
                  data-target="#atomic-coordinates-body-{{ subset.pk }}">
            Atomic coordinates (click to expand)
          </button>
        </div>
      {% endif %}
      <div class="collapse" id="atomic-coordinates-body-{{ subset.pk }}"></div>
    {% endfor %}
  </div>
</div>

materials/templates/materials/license_note.html
<div class="col-md-12">
  <br>
  <div class="card card-item">
    <div class="card-header">
      <h4>License</h4>
    </div>
    <div class="card-body">
      All data is available under the Creative Commons license with attribution clause, described <a href="https://creativecommons.org/licenses/by/4.0/">here</a> and, in its full text, <a href="https://creativecommons.org/licenses/by/4.0/legalcode">here</a>.
    </div>
  </div>
</div>

materials/templates/materials/linked_data.html
{% extends 'materials/base.html' %}

{# List all data sets linked to a given data set #}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h3>These data sets are directly related (linked) to each other</h3>
    </div>
    <div class="card-body">
      <div class="row">
        {% for dataset in object_list %}
          {% if user == dataset.created_by or dataset.visible %}
            <div class="col-md-6">
              <div class="card card-item">
                {% if not dataset.visible %}
                  <div style="background:#fadb9b">
                {% endif %}
                <div class="card-header">
                  <h5>{{ dataset.primary_property.name|capfirst }}</h5>
                  {% if user == dataset.created_by %}
                    {% include 'materials/dataset_buttons.html' with system=dataset.system %}
                  {% endif %}
                </div>
                {% if not dataset.visible %}
                  </div>
                {% endif %}
                <div class="card-body">
                  {% include 'materials/dataset_contents.html' with with_reference=True with_all_entries=True %}
                </div>
              </div>
              <br>
            </div>
          {% endif %}
        {% endfor %}
        {% include "materials/license_note.html" %}
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  {% include 'materials/dataset_scripts.html' with datasets=object_list %}
{% endblock %}

materials/templates/materials/reference_format.html
{% for author in ref.authors.all %}
  {% if forloop.last and not forloop.first %}and{% endif %}

  {% for fn in author.splitFirstName %}
    {{ fn.0 }}.
  {% endfor %}

  {{ author.last_name }}{% if not forloop.first or forloop.revcounter0 != 1 %},{% endif %}

{% endfor %}

{% if ref.title %}
  <i>{{ ref.title }}</i>,
{% endif %}

{% if ref.journal %}
  {{ ref.journal }}
{% endif %}

{% if ref.vol %}
  <strong>{{ ref.vol }}</strong>,
{% endif %}

{% if ref.pages_start %}
  {{ ref.pages_start }}{% if ref.pages_end %}&#8209;{{ ref.pages_end }}
  {% endif %}
{% endif %}

{% if ref.year %}
  ({{ ref.year }}).
{% endif %}

{% if ref.doi_isbn %}
  doi:&nbsp;{{ ref.doi_isbn }}.
{% endif %}

materials/templates/materials/search.html
{% extends 'materials/base.html' %}

{% block body %}
  <br>
  <div class="card card-default">
    <div class="card-header">
      <h5>Search for Materials</h5>
    </div>
    <div class="card-body">
      <form id="search-system" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="search_text">Search term: </label>
          <div class="input-group">
            <div class="input-group-prepend">
              <select id="search_term" name="search_term" class="selectpicker">
                {% for search_term in search_terms %}
                  <option value="{{ search_term.0 }}">{{ search_term.1 }}</option>
                {% endfor %}
              </select>
            </div>
            <input id="search_text" class="form-control" type="text" name="search_text" required/>
            <div class="input-group-append">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </div>
      </form>
      <div class="alert alert-info" id="explanatory_text">
        Search for all or part of a chemical formula, e.g. CH3NH3PbI3 or MAPbI3
      </div>
      <br>
      <ul id="results" class="list-group">
      </ul>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
   $('#search_text').attr("placeholder", "Search for all or part of a chemical formula, e.g. CH3NH3PbI3 or MAPbI3");
   $('#search_term').change(function() {
     if(this.value == "exciton_emission") {
       text = "Search by range using >, >=, <, <=, or a combination, e.g. >=400";
       $('#search_text').attr("placeholder", text);
       $('#explanatory_text').text(text);
     } else if(this.value == "formula") {
       text = "Search for all or part of a chemical formula, e.g. CH3NH3PbI3 or MAPbI3"
       $('#search_text').attr("placeholder", text);
       $('#explanatory_text').text(text);
     } else if(this.value == "organic") {
       text = "Search for all or part of an organic component, e.g. CH3NH3";
       $('#explanatory_text').text(text);
       $('#search_text').attr("placeholder", text);
     } else if(this.value == "inorganic") {
       text = "Search for all or part of an inorganic component, e.g. PbI3";
       $('#search_text').attr("placeholder", text);
       $('#explanatory_text').text(text);
     } else {
       text = "";
       $('#search_text').attr("placeholder", text);
       $('#explanatory_text').text(text);
     }
   });
   let search_system = document.getElementById('search-system');
   search_system.addEventListener('submit', function(event) {
     event.preventDefault();
     const form_data = new FormData(this);
     axios.post('{% url 'materials:search' %}', form_data)
          .then(response => {
            document.getElementById('results').innerHTML = response['data'];
          });
   });
  </script>
{% endblock %}

materials/templates/materials/search_results.html
{% if systems.count > 0 %}
  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th>Compound Name</th>
        <th>Chemical Formula</th>
        <th>Alternate Names</th>
        <th>Organic Component</th>
        <th>Inorganic Component</th>
      </tr>
    </thead>
    <tbody>
      {% for system in systems %}
        <tr>
          <td><a href="{% url 'materials:system' pk=system.pk %}">{{ system.compound_name }}</a></td>
          <td><a href="{% url 'materials:system' pk=system.pk %}">{{ system.formula }}</a></td>
          <td>
            <ul style="padding: 0px; list-style-type: none" id="authors-list">
              {% for name in system.listAlternateNames %}
                <li><a href="{% url 'materials:system' pk=system.pk %}">{{ name }}</a></li>
              {% endfor %}
            </ul>
          </td>
          <td>{{ system.organic }}</td>
          <td>{{ system.inorganic }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning" role="alert">No results found. Please retry with a new search term</p>
{% endif %}

materials/templates/materials/system.html
{% extends 'materials/base.html' %}

{% comment %}
List of data sets for a specific material. Only the representative
data sets corresponding to each property are shown.
{% endcomment %}

{% block body %}
  {% load static %}
  <div class="card card-default">
    <div class="card-header">
      {% if user.is_superuser and dataset_list.first %}
        <a href="/admin/materials/system/{{ dataset_list.first.system.pk }}/change/">
          <button type="button" class="btn btn-success" style="float: right">
            Edit System Data
          </button>
        </a>
      {% endif %}
      <h3>{{ dataset_list.first.system.compound_name }}</h3>
    </div>

    <div class="card-body">
      <div class="row">

        {% for dataset in dataset_list %}
          {% if dataset.representative %}
            {% if user == dataset.created_by or dataset.visible %}
              {% comment %}
              In case of atomic structures use a wider column to make
              room for the JSmol visualization below
              {% endcomment %}
              <div class="col-md-{% if dataset.primary_property.name == 'atomic structure'%}12{% else %}6{% endif %}">
                <div class="card card-item">
                  {% if not dataset.visible %}
                    <div style="background:#fadb9b">
                  {% endif %}
                  <div class="card-header">
                    <h5>
                      {{ dataset.primary_property.name|capfirst }}
                      {% if dataset.verified_by.exists %}
                        <span class="badge badge-success">Verified</span>
                      {% endif %}
                    </h5>
                    {% if user == dataset.created_by %}
                      {% include 'materials/dataset_buttons.html' with system=dataset_list.first.system %}
                    {% endif %}
                  </div>
                  {% if not dataset.visible %}
                    </div>
                  {% endif %}
                  <div class="card-body">
                    {% if dataset.primary_property.name == 'atomic structure'%}
                    <div class="row">
                      <div class="col-md-6">
                        {% include 'materials/dataset_contents.html' with with_reference=True with_all_entries=True skip_atomic_structure=True %}
                      </div>
                      <div class="col-md-6">
                        {% include 'materials/jsmol_card.html' %}
                      </div>
                    </div>
                    {% else %}
                    {% include 'materials/dataset_contents.html' with with_reference=True with_all_entries=True %}
                    {% endif %}
                  </div>
                </div>
                <br>
              </div>
            {% endif %}
          {% endif %}
        {% endfor %}

        {% include "materials/license_note.html" %}
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="{% static 'jsmol/JSmol.min.js' %}"></script>
  <script>
   {% if dataset_list.first and dataset_list.first.system.pk %}
   $.get("{% url 'materials:get_jsmol_input' pk=dataset_list.first.system.pk %}", function(response) {
     if (response) {
       $('#jmol').html(Jmol.getAppletHtml('jmol', {
         script: response,
         j2sPath: "{% static 'jsmol/j2s' %}",
         height: 450,
         width: 470,
       }));
     } else {
       var el = document.getElementById('jmol');
       el.innerHTML = 'Atomic coordinates not available for this data set.';
     }
   });
   {% endif %}
  </script>
  {% include 'materials/dataset_scripts.html' with datasets=dataset_list %}
{% endblock %}