accounts/urls.py
# This file is covered by the BSD license. See LICENSE in the root directory.
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetDoneView
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout', LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'),
    path('register', views.register, name='register'),
    path('activate/<str:uid>/<slug:token>', views.activate, name='activate'),
    path('profile', views.profile, name='profile'),
    path('change-password', views.change_password, name='change_password'),
    path('reset-password', PasswordResetView.as_view(
        template_name='accounts/reset_password.html',
        success_url='/accounts/reset-password/done',
        email_template_name='accounts/reset_password_email.html'),
         name='reset_password'),
    path('reset-password/done', PasswordResetDoneView.as_view(
        template_name='accounts/reset_password_done.html')),
    path('reset-password/confirm<str:uidb64>/<slug:token>/',
         PasswordResetConfirmView.as_view(
             template_name='accounts/reset_password_confirm.html',
             success_url='/accounts/reset-password/complete'),
         name='password_reset_confirm'),
    path('reset-password/complete', PasswordResetCompleteView.as_view(
        template_name='accounts/reset_password_complete.html')),
]

mainproject/urls.py
# This file is covered by the BSD license. See LICENSE in the root directory.
"""MatD3 URL Configuration.

"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import generic

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', generic.TemplateView.as_view(
        template_name='mainproject/home.html'), name='index'),
    path('contact/', generic.TemplateView.as_view(
        template_name='mainproject/contact.html'), name='contact'),
    path('contributors/', views.contributors, name='contributors'),
    path('materials/', include('materials.urls')),
    path('accounts/', include('accounts.urls')),
    path('nested_admin/', include('nested_admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# This file is covered by the BSD license. See LICENSE in the root directory.
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=200, blank=True)
    institution = models.CharField(max_length=200, blank=True)
    website = models.URLField(blank=True)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

accounts/forms.py
# This file is covered by the BSD license. See LICENSE in the root directory.
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, required=True)

    class Meta:
        model = User
        fields = (
            'username', 'first_name', 'last_name', 'email', 'password1',
            'password2'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].help_text = ''
            self.fields[name].widget.attrs['class'] = 'form-control'


class EditUserForm(forms.ModelForm):
    email = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].widget.attrs['class'] = 'form-control'


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control-file'


class ChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].widget.attrs['class'] = 'form-control'

accounts/views.py
# This file is covered by the BSD license. See LICENSE in the root directory.
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.http import urlsafe_base64_decode

from .forms import ChangePasswordForm
from .forms import EditProfileForm
from .forms import EditUserForm
from .forms import RegistrationForm
from .tokens import account_activation_token


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user.email_user(
                'Activate Your HybriD3 Account',
                render_to_string('accounts/activation_email.html', {
                    'user': user,
                    'domain': get_current_site(request),
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
            )
            messages.success(
                request, 'Confirmation email has been sent. Check your email.')
            form = RegistrationForm()
    else:
        form = RegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})


def activate(request, uid, token):
    try:
        pk = urlsafe_base64_decode(uid)
        user = User.objects.get(pk=pk)
        if not account_activation_token.check_token(user, token):
            raise User.DoesNotExist
        user.is_active = True
        user.save()
        login(request, user)
        Group.objects.get(name='users').user_set.add(user)
        # Notify all superusers of the new user
        email_addresses = list(User.objects.filter(
            is_superuser=True).values_list('email', flat=True))
        send_mail('HybriD3 database: new user created', '', 'hybrid3info',
                  email_addresses,
                  fail_silently=False,
                  html_message=(f'The account of "{user.username}" is '
                                'waiting to be elevated to staff status.'))
        messages.success(request, 'Account confirmed.')
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        messages.error(request, 'Activation link is invalid!')
    return redirect(reverse('accounts:profile'))


@login_required
def profile(request):
    user = request.user
    user_profile = user.userprofile
    if request.method == 'GET':
        user_form = EditUserForm(instance=request.user)
        user_profile_form = EditProfileForm(instance=user_profile)
        return render(request, 'accounts/profile.html', {
            'user_form': user_form,
            'user_profile_form': user_profile_form
        })
    elif request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        user_profile_form = EditProfileForm(request.POST,
                                            instance=user_profile)
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.save()
            user_profile_form.save()
            messages.success(request, 'Profile information updated')
        else:
            messages.error(request, 'Could not update profile information')
        return redirect(reverse('accounts:profile'))


@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Password successfully changed')
            return redirect(reverse('accounts:profile'))
        else:
            messages.error(request,
                           'Incorrect password or new passwords not matching')
    form = ChangePasswordForm(user=request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

accounts/templates/accounts/activate.html
{% extends 'accounts/base.html' %}

{% block head %}
  <title>Activate Account</title>
{% endblock %}

{% block body %}
  <div class="container">
    <h4>{{ text }}</h4>
  </div>
{% endblock %}

accounts/templates/accounts/activation_email.html
{% autoescape off %}
  Hi {{ user.first_name }},

  Please click on the link below to confirm your registration on the HybriD&#xb3; materials database,

  http://{{ domain }}{% url 'accounts:activate' uid=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/base.html
{% extends 'mainproject/base.html' %}

{% block navbar %}
  <nav class="navbar navbar-expand-md">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">HybriD&#xb3; materials account</a>
      <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse"
              data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:change_password' %}">Change Password</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:reset_password' %}">Reset Password</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register'%}">Register</a>
            </li>
          </ul>
        {% endif %}
      </div>
  </nav>
{% endblock %}

accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Change Password</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Login</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block body %}
  <h1>You have logged out</h1>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Profile</h4>
    </div>
    <div class="card-body">
      <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ user_profile_form.as_p }}
        {{ user_profile_form.errors }}
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Register for HybriD&#xb3; database</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Register</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Password reset</h4>
    </div>
    <div class="card-body">
      <p>
        Enter your email address below and we'll email instructions for setting a new one.
      </p>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Reset password</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Password reset complete</h4>
    </div>
    <div class="card-body">
      <a href="{% url 'accounts:login' %}">
        <button type="submit" class="btn btn-primary">Login</button>
      </a>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Enter new password</h4>
    </div>
    <div class="card-body">
      <p>
        Please enter your new password twice.
      </p>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Change my password</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'accounts/base.html' %}

{% block body %}
  <div class="card card-default">
    <div class="card-header">
      <h4>Password reset</h4>
    </div>
    <div class="card-body">
      <p>
        An email has been sent with instructions for setting your password to the address specified.
      </p>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% autoescape off %}
  <p>You're receiving this email because you requested a password reset for your HybriD3 account.</p>

  Please go to the following page and choose a new password:
  {% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
  {% endblock %}
  Your username: {{ user.get_username }}
{% endautoescape %}